server:
  port: 8080

spring:

  application:
    name: fc-ms-balance

  datasource:
    url: jdbc:h2:mem:balance-db
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: accounts-consumer