
POST http://localhost:8080/clients
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "client_id": "c1480326-c000-4e6d-9cf3-2786c10e6d4d"
}

###

POST http://localhost:8080/transactions
Content-Type: application/json

{
    "account_id_from": "dd37c557-0522-43ea-9717-11421ba134b6",
    "account_id_to": "b4d0e6ce-4695-4aba-9a0a-bddd54e7a903",
    "amount": 10
}