
POST http://localhost:8080/clients
Content-Type: application/json

{
    "name": "John Doe 1",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "client_id": "6fb25e7d-044b-4878-abc1-8aafa68f3dcf"
}

###

POST http://localhost:8080/transactions
Content-Type: application/json

{
    "account_id_from": "7df07094-3683-4cb5-adf7-96505618331f",
    "account_id_to": "41c7648c-f6b6-4c4c-8d45-106af13e2386",
    "amount": 1
}